name: Backend Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('./country-list-application/backend/app/pyproject.toml') }}-test
      - name: Install Poetry
        if: steps.cache.outputs.cache-hit != 'true'
        run: python -m pip install --upgrade pip && pip install poetry && poetry config virtualenvs.create false
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd country-list-application/backend/app && poetry install
      - name: Test with pytest
        run: cd ./country-list-application/backend/app && bash scripts/test.sh
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./country-list-application/backend/app/.coverage
          fail_ci_if_error: true