version: "3.9"
services:
  backend:
    image: "country-list-backend:0.1.0"
    restart: always
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

  server:
    image: "country-list-server:0.1.0"
    restart: always
    depends_on:
      - backend
    build:
      context: ..
      dockerfile: ./country-list-application/server/server.dockerfile
    ports:
      - 8899:80